version: '2'
networks:
  lb_web:
    external: true
  back:
    driver: bridge
services:
  web:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
    - VIRTUAL_HOST
    networks:
    - back
    - lb_web
  collabora:
    image: collabora/code
    cap_add:
    - MKNOD
    env_file:
    - ./env
    networks:
    - back
